version: "3.9"

services:
  app:
    image: typoglycemia-dev:1.0.0
    build:
      context: dockerfiles/dev
    working_dir: /app
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
      - yarn-cache:/usr/local/share/.cache/yarn/v6
    tty: true

volumes:
  node_modules:
  yarn-cache:
